title: John Doe # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
    A software development professional with a focus on testing - the art of having relevant on-time information about the product. 
    I am passionate about building new things but also about finding out how well do they work.
    During my career, I was
    • Working closely side by side with developers, bringing tests and testability into the product early in design stages, providing shorter feedback loops and helping get a better system view of the product.
    • Building trustable reports of the product's quality by using it the way users expect to and ways they never intended to, getting the data to back it up then use a wider system view to combine it all into meaningful results. 
    • Mentoring and inspiring others to
    o Blend quality in starting from the design phase and through development 
    o Make testers equal and respected members of any development teams. 
    • Testing on a multitude of embedded, mobile, desktop and enterprise products and operating systems.
    • Holding an ISTQB foundation certificate, and past member of the Israeli advisory board ITCB.  <br><br>  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/oren-reshef-9862276/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
